name: Tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pyv: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyv }}
        cache: 'pip'

    - name: install
      run: |
        pip install --upgrade pip wheel
        pip install -e . pytest

    - name: decrypt token
      run: |
        openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEY }} -iv ${{ secrets.ENCRYPTED_IV }} -in .google_drive_tokens.enc -out tfile.pickle -d

    - name: run tests
      timeout-minutes: 15
      run: pytest -vv
